In [1]:
from data.data import load_cifar_10, load_cifar_10_other

/home/joel/miniconda3/envs/py310/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
trainldr, validldr = load_cifar_10()
trainldr_other, validldr_other = load_cifar_10_other()


Files already downloaded and verified
trainloader.data.shape: Dataset CIFAR10
    Number of datapoints: 50000
    Root location: ./data
    Split: Train
    StandardTransform
Transform: Compose(
               RandomCrop(size=(32, 32), padding=4)
               RandomHorizontalFlip(p=0.5)
               ToTensor()
               Normalize(mean=[0.49139968, 0.48215841, 0.44653091], std=[0.24703223, 0.24348513, 0.26158784])
           )
Files already downloaded and verified
testloader.data.shape: Dataset CIFAR10
    Number of datapoints: 10000
    Root location: ./data
    Split: Test
    StandardTransform
Transform: Compose(
               ToTensor()
               Normalize(mean=[0.49139968, 0.48215841, 0.44653091], std=[0.24703223, 0.24348513, 0.26158784])
           )
augment: True batch_size: 64
Files already downloaded and verified


In [3]:
x1=iter(trainldr).next()
x2=iter(trainldr_other).next()


In [4]:
from utils import set_seed

set_seed()

Random seed set as 42


In [6]:
x1[0][0][0], x2[0][0][0]

(tensor([[-1.9892, -1.9892, -1.9892,  ...,  0.7889,  0.7571,  0.6936],
         [-1.9892, -1.9892, -1.9892,  ...,  0.7095,  0.9794,  1.0746],
         [-1.9892, -1.9892, -1.9892,  ...,  0.7412,  1.3921,  1.5191],
         ...,
         [-1.9892, -1.9892, -1.9892,  ..., -1.9892, -1.9892, -1.9892],
         [-1.9892, -1.9892, -1.9892,  ..., -1.9892, -1.9892, -1.9892],
         [-1.9892, -1.9892, -1.9892,  ..., -1.9892, -1.9892, -1.9892]]),
 tensor([[-1.9889, -1.9889, -1.9889,  ..., -1.9889, -1.9889, -1.9889],
         [-1.9889, -1.9889, -1.9889,  ..., -1.9889, -1.9889, -1.9889],
         [-1.9889, -1.9889, -1.9889,  ..., -0.1000, -0.0841,  0.1857],
         ...,
         [-1.9889, -1.9889, -1.9889,  ..., -0.0206, -0.0524, -0.0841],
         [-1.9889, -1.9889, -1.9889,  ...,  0.2333,  0.2492,  0.2175],
         [-1.9889, -1.9889, -1.9889,  ...,  0.3127,  0.2968,  0.2492]]))

(tensor([[ 0.6936,  0.6936,  0.6777,  ...,  0.6301, -1.9892, -1.9892],
         [ 0.9476,  0.9794,  1.0270,  ...,  0.4237, -1.9892, -1.9892],
         [ 1.3921,  1.3445,  1.2810,  ...,  0.3920, -1.9892, -1.9892],
         ...,
         [-1.9892, -1.9892, -1.9892,  ..., -1.9892, -1.9892, -1.9892],
         [-1.9892, -1.9892, -1.9892,  ..., -1.9892, -1.9892, -1.9892],
         [-1.9892, -1.9892, -1.9892,  ..., -1.9892, -1.9892, -1.9892]]),
 
 tensor([[-1.9889, -1.9889, -1.9889,  ..., -1.9889, -1.9889, -1.9889],
         [-1.9889, -1.9889, -1.9889,  ..., -1.9889, -1.9889, -1.9889],
         [-1.9889, -1.9889, -1.9889,  ..., -1.9889, -1.9889, -1.9889],
         ...,
         [-1.9889, -1.9889, -1.9889,  ...,  0.7730,  0.8683,  0.9635],
         [-1.9889, -1.9889, -1.9889,  ...,  0.6937,  0.8206,  1.0111],
         [-1.9889, -1.9889, -1.9889,  ...,  0.6778,  0.8048,  0.8683]]))

In [22]:
trainldr.dataset

Dataset CIFAR10
    Number of datapoints: 50000
    Root location: ./data
    Split: Train
    StandardTransform
Transform: Compose(
               RandomCrop(size=(32, 32), padding=4)
               RandomHorizontalFlip(p=0.5)
               ToTensor()
               Normalize(mean=[0.49139968, 0.48215841, 0.44653091], std=[0.24703223, 0.24348513, 0.26158784])
           )

In [23]:
trainldr_other.dataset

Dataset CIFAR10
    Number of datapoints: 50000
    Root location: ./data
    Split: Train
    StandardTransform
Transform: Compose(
               RandomCrop(size=(32, 32), padding=4)
               RandomHorizontalFlip(p=0.5)
               ToTensor()
               Normalize(mean=[0.4913725490196078, 0.4823529411764706, 0.4466666666666667], std=[0.24705882352941178, 0.24352941176470588, 0.2615686274509804])
           )

In [2]:
[x/255.0 for x in [125.3, 123.0, 113.9]]

[0.4913725490196078, 0.4823529411764706, 0.4466666666666667]

In [3]:
[x/255.0 for x in [63.0, 62.1, 66.7]]

[0.24705882352941178, 0.24352941176470588, 0.2615686274509804]

In [ ]:
[0.49139968, 0.48215841, 0.44653091]

In [4]:
[0.24703223, 0.24348513, 0.26158784]

[0.24703223, 0.24348513, 0.26158784]

In [1]:
import joblib
import torch

/home/joel/miniconda3/envs/py310/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [109]:
def compare_models(model_1, model_2):
    models_differ = 0
    for key_item_1, key_item_2 in zip(model_1.state_dict().items(), model_2.state_dict().items()):
        if torch.equal(key_item_1[1], key_item_2[1]):
            print('Its a match at', key_item_1[0])
            pass
        else:
            models_differ += 1
            if (key_item_1[0] == key_item_2[0]):
                print('Mismatch found at', key_item_1[0])
                # dt1, dt2 = key_item_1[1][0][0], key_item_2[1][0][0]
                dt1, dt2 = key_item_1, key_item_2
                # print('1:', dt1[1].cpu().detach().numpy())#[0])#[0])
                # print('2:', dt2[1].cpu().detach().numpy())#[0])#[0])
                # print('1:', dt1.cpu().detach().numpy())
                # print('2:', dt2.cpu().detach().numpy())#[0])#[0])
                # print(torch.allclose(dt1, dt2))
                # print(torch.sum(torch.eq(dt1, dt2)).item()/dt1.nelement())
                # break
            else:
                raise Exception('Names are different!')
    if models_differ == 0:
        print('Models match perfectly! :)')

In [215]:
model = joblib.load('model.pkl')
model_other = joblib.load('model_other.pkl')
compare_models(model, model_other)

Its a match at conv1.weight
Its a match at block1.layer.0.bn1.weight
Its a match at block1.layer.0.bn1.bias
Its a match at block1.layer.0.bn1.running_mean
Its a match at block1.layer.0.bn1.running_var
Its a match at block1.layer.0.bn1.num_batches_tracked
Its a match at block1.layer.0.conv1.weight
Its a match at block1.layer.1.bn1.weight
Its a match at block1.layer.1.bn1.bias
Its a match at block1.layer.1.bn1.running_mean
Its a match at block1.layer.1.bn1.running_var
Its a match at block1.layer.1.bn1.num_batches_tracked
Its a match at block1.layer.1.conv1.weight
Its a match at block1.layer.2.bn1.weight
Its a match at block1.layer.2.bn1.bias
Its a match at block1.layer.2.bn1.running_mean
Its a match at block1.layer.2.bn1.running_var
Its a match at block1.layer.2.bn1.num_batches_tracked
Its a match at block1.layer.2.conv1.weight
Its a match at block1.layer.3.bn1.weight
Its a match at block1.layer.3.bn1.bias
Its a match at block1.layer.3.bn1.running_mean
Its a match at block1.layer.3.bn1.r

In [216]:
torch.set_printoptions(precision=12)
model.state_dict()['bn1.running_mean'][-5:], model_other.state_dict()['bn1.running_mean'][-5:]

(tensor([-0.462020933628,  1.668135166168, -1.316789984703, -0.030693136156,
          0.966317713261], device='cuda:0'),
 tensor([-0.462020933628,  1.668135166168, -1.316789984703, -0.030693136156,
          0.966317713261], device='cuda:0'))

(tensor([-0.395167261362,  0.225659757853, -0.205155521631,  0.262294024229,
          0.177738666534], device='cuda:0'),
          
 tensor([-0.395167440176,  0.225659757853, -0.205155536532,  0.262294083834,
          0.177738696337], device='cuda:0'))

In [213]:
model.state_dict()['bn1.running_mean'][-5:] == model_other.state_dict()['bn1.running_mean'][-5:]

tensor([True, True, True, True, True], device='cuda:0')

In [214]:
model.state_dict()['bn1.num_batches_tracked'], model_other.state_dict()['bn1.num_batches_tracked']

(tensor(782, device='cuda:0'), tensor(782, device='cuda:0'))

In [210]:
1096-314

782

In [133]:
model.state_dict()['conv1.weight'].grad

In [72]:
model.state_dict()['conv1.weight'].cpu().detach().numpy()[0][0]

array([[-0.01319661,  0.02097806,  0.07708647],
       [-0.00879365, -0.02745198,  0.00404509],
       [-0.17060097,  0.00236645,  0.0463047 ]], dtype=float32)

In [73]:
model_other.state_dict()['conv1.weight'].cpu().detach().numpy()[0][0]

array([[-0.01319698,  0.02097518,  0.0770831 ],
       [-0.0087932 , -0.02745287,  0.00404501],
       [-0.17060001,  0.00236583,  0.04630519]], dtype=float32)

In [93]:
model.state_dict()['block1.layer.1.bn1.running_mean'].cpu().detach().numpy()

array([-0.00064227,  0.00395768,  0.01842655, -0.00622914,  0.00420009,
        0.00018294,  0.02315863, -0.00022504, -0.00927119, -0.01681951,
        0.00947453, -0.00023506, -0.00064698, -0.00877169,  0.0112449 ,
        0.00470695, -0.01674166,  0.00863675, -0.00678893, -0.00778124,
       -0.00665251,  0.00940233, -0.00718217, -0.01163542,  0.03688512,
        0.002951  ,  0.07543098, -0.05768278,  0.00512432,  0.03226265,
        0.12774254,  0.00478267, -0.11099427, -0.0274372 ,  0.11027243,
        0.09518541], dtype=float32)

In [94]:
model_other.state_dict()['block1.layer.1.bn1.running_mean'].cpu().detach().numpy()

array([-0.00064227,  0.00395768,  0.01842655, -0.00622914,  0.00420009,
        0.00018294,  0.02315863, -0.00022504, -0.00927119, -0.01681951,
        0.00947453, -0.00023506, -0.00064698, -0.00877169,  0.0112449 ,
        0.00470695, -0.01674166,  0.00863675, -0.00678893, -0.00778124,
       -0.00665251,  0.00940233, -0.00718217, -0.01163542,  0.03688512,
        0.002951  ,  0.07543098, -0.05768278,  0.00512432,  0.03226264,
        0.12774254,  0.00478266, -0.11099424, -0.02743721,  0.11027243,
        0.0951854 ], dtype=float32)

In [95]:
model.state_dict()['block1.layer.0.bn1.num_batches_tracked'].cpu().detach().numpy()

array(1)

In [96]:
model_other.state_dict()['block1.layer.0.bn1.num_batches_tracked'].cpu().detach().numpy()

array(1)

In [30]:
t1 = torch.tensor([[[ 0.1005, -0.0445,  0.0950],
         [-0.1138,  0.1395, -0.0370],
         [-0.0035, -0.0637, -0.0009]],

        [[ 0.0412,  0.1025,  0.0709],
         [ 0.0337,  0.0216,  0.0087],
         [-0.0028, -0.0428, -0.0132]],

        [[ 0.0994,  0.0065, -0.0915],
         [-0.0065,  0.0593, -0.0698],
         [ 0.0746,  0.0531,  0.1894]]], device='cuda:0')

In [48]:
t2=torch.tensor([[[ 0.1check_trainloader005, -0.0445,  0.0950],
         [-0.1138,  0.1395, -0.0370],
         [-0.0035, -0.0637, -0.0009]],

        [[ 0.0412,  0.1025,  0.0709],
         [ 0.0337,  0.0216,  0.0087],
         [-0.0028, -0.0428, -0.0132]],

        [[ 0.0994,  0.0065, -0.0915],
         [-0.0065,  0.0593, -0.0698],
         [ 0.0746,  0.0531,  0.1894]]], device='cuda:0')

In [49]:
torch.eq(t1, t2)

tensor([[[True, True, True],
         [True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True],
         [True, True, True]]], device='cuda:0')

In [54]:
print(torch.sum(torch.eq(t1, t2)).item()/t1.nelement())

1.0


# compare the outputs

In [134]:
output = joblib.load('outputs.pkl')
output_other = joblib.load('outputs_other.pkl')


In [135]:
torch.equal(output, output_other)

False

In [136]:
output[0][-5:]

tensor([ 0.288734197617, -0.213807314634, -0.777192175388,  0.009351372719,
         0.234167441726], device='cuda:0', grad_fn=<SliceBackward0>)

tensor([ 0.288734197617, -0.213807314634, -0.777192175388,  0.009351372719,
         0.234167441726], device='cuda:0', grad_fn=<SliceBackward0>)

In [137]:
output_other[0][-5:]

tensor([ 0.288733720779, -0.213807061315, -0.777192115784,  0.009351611137,
         0.234167322516], device='cuda:0', grad_fn=<SliceBackward0>)

tensor([ 0.288733661175, -0.213807106018, -0.777191996574,  0.009351551533,
         0.234167397022], device='cuda:0', grad_fn=<SliceBackward0>)

# compare the inputs

In [138]:
input = joblib.load('inputs.pkl')
input_other = joblib.load('inputs_other.pkl')


In [139]:
torch.equal(input, input_other)

True

In [140]:
input.shape

torch.Size([64, 3, 32, 32])

In [141]:
input[0][0][0][:5]

tensor([-1.988888859749, -1.988888859749, -1.988888859749, -1.988888859749,
        -1.988888859749], device='cuda:0')

In [142]:
input_other[0][0][0][:5]

tensor([-1.988888859749, -1.988888859749, -1.988888859749, -1.988888859749,
        -1.988888859749], device='cuda:0')